export const REQUEST_WEATHER_PENDING = "REQUEST_WEATHER_PENDING";
export const REQUEST_WEATHER_SUCCESS = "REQUEST_WEATHER_SUCCESS";
export const REQUEST_WEATHER_FAILED = "REQUEST_WEATHER_FAILED";
export const CLEAR_WEATHER_FORM = "CLEAR_WEATHER_FORM";
